# Generated by Django 5.2.16 on 2026-07-19 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0003_projectboundary'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerCurve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('air_density_ref_kg_m3', models.FloatField(default=1.225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turbine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_curves', to='gis.turbinemodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnergyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('wind_distribution', models.JSONField(default=list)),
                ('wake_loss_fraction', models.FloatField(default=0.0)),
                ('method_version', models.CharField(default='gross_energy_v1', max_length=64)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_assessments', to='projects.project')),
                ('power_curve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='energy.powercurve')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerCurvePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wind_speed_m_s', models.FloatField()),
                ('power_kw', models.FloatField()),
                ('power_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='energy.powercurve')),
            ],
            options={
                'ordering': ['wind_speed_m_s'],
                'constraints': [models.UniqueConstraint(fields=('power_curve', 'wind_speed_m_s'), name='uniq_power_curve_wind_speed')],
            },
        ),
    ]
