# Generated by Django 5.2.16 on 2026-07-19 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
        ('gis', '0003_projectboundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtCurve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('air_density_ref_kg_m3', models.FloatField(default=1.225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turbine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_curves', to='gis.turbinemodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CtCurvePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wind_speed_m_s', models.FloatField()),
                ('ct', models.FloatField()),
                ('ct_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='energy.ctcurve')),
            ],
            options={
                'ordering': ['wind_speed_m_s'],
                'constraints': [models.UniqueConstraint(fields=('ct_curve', 'wind_speed_m_s'), name='uniq_ct_curve_wind_speed')],
            },
        ),
    ]
