# Generated by Django 5.2.16 on 2026-07-19 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateReferenceSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epsg_code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('auth_name', models.CharField(default='EPSG', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coordinate reference system',
                'verbose_name_plural': 'Coordinate reference systems',
                'ordering': ['epsg_code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCRS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('horizontal', 'Horizontal'), ('display', 'Display')], default='horizontal', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_links', to='gis.coordinatereferencesystem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs_links', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'role'), name='uniq_project_crs_role')],
            },
        ),
    ]
