# Generated by Django 5.2.16 on 2026-07-19 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurbineManufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TurbineModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hub_height_m', models.FloatField()),
                ('rotor_diameter_m', models.FloatField()),
                ('rated_power_kw', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='gis.turbinemanufacturer')),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TurbinePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turbine_positions_created', to=settings.AUTH_USER_MODEL)),
                ('crs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turbine_positions', to='gis.coordinatereferencesystem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbine_positions', to='projects.project')),
                ('turbine_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='gis.turbinemodel')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddConstraint(
            model_name='turbinemodel',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='uniq_turbine_manufacturer_model_name'),
        ),
        migrations.AddConstraint(
            model_name='turbineposition',
            constraint=models.UniqueConstraint(fields=('project', 'label'), name='uniq_project_turbine_label'),
        ),
    ]
