# Generated by Django 5.2.16 on 2026-07-19 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('structure_type', models.CharField(choices=[('mast', 'Met mast'), ('lidar', 'Lidar'), ('sodar', 'Sodar')], max_length=16)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_campaigns', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('variable', models.CharField(choices=[('wind_speed', 'Wind speed'), ('wind_direction', 'Wind direction'), ('temperature', 'Temperature'), ('pressure', 'Pressure')], max_length=32)),
                ('height_m', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='meteo.measurementcampaign')),
            ],
            options={
                'ordering': ['height_m', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('qc_flag', models.CharField(choices=[('ok', 'OK'), ('missing', 'Missing'), ('range', 'Out of range'), ('frozen', 'Frozen'), ('excluded', 'Excluded')], default='ok', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='meteo.measurementcampaign')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='meteo.sensor')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('campaign', 'code'), name='uniq_campaign_sensor_code'),
        ),
        migrations.AddIndex(
            model_name='timeseriespoint',
            index=models.Index(fields=['campaign', 'timestamp'], name='meteo_times_campaig_5f5bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriespoint',
            index=models.Index(fields=['sensor', 'timestamp'], name='meteo_times_sensor__5b54c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeseriespoint',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='uniq_sensor_timestamp'),
        ),
    ]
