# Generated by Django 5.2.16 on 2026-07-19 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_id', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('experimental', 'Experimental'), ('approved_default', 'Approved default'), ('deprecated', 'Deprecated')], default='experimental', max_length=32)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['method_id', 'version'],
                'constraints': [models.UniqueConstraint(fields=('method_id', 'version'), name='uniq_calculation_method_id_version')],
            },
        ),
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(max_length=128)),
                ('application_version', models.CharField(default='0.1.0', max_length=32)),
                ('input_data_version', models.CharField(blank=True, default='', max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('validation_status', models.CharField(choices=[('not_validated', 'Not validated'), ('smoke_ok', 'Smoke OK'), ('benchmark_ok', 'Benchmark OK'), ('failed_validation', 'Failed validation')], default='not_validated', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_runs_created', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='calculations.calculationmethod')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_runs', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='calculations.calculationrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
